//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id_record { get; set; }
        public int id_group { get; set; }
        public int id_discipline { get; set; }
        public string room { get; set; }
        public int id_teacher { get; set; }
        public string data { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
    
        public virtual Disciplines Disciplines { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
